# Generated by Django 4.1.4 on 2023-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.TextField()),
                ('total_price', models.FloatField()),
                ('customer', models.CharField(max_length=255)),
                ('paid_amount', models.FloatField()),
                ('due_amount', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
